name: Build

on:
  pull_request:
  push:
  schedule:
    # Prime the caches every Monday
    - cron: 0 1 * * MON

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        ocaml-compiler:
          - "4.14"
          - "5.2"
        include:
          - os: ubuntu-latest
            ocaml-compiler: "4.08"

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout tree
        uses: actions/checkout@v4

      - name: Set-up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
          opam-pin: false

      - run: opam pin add ocsigen-start.dev . --no-action

      - run: opam install .

      - run: mkdir -p template

      - run: opam exec -- eliom-distillery -name template -template os.pgocaml

      - run: opam install -y .
        working-directory: template

      - run: make USE_SASS=no db-init db-create db-schema
        working-directory: template

      - run: opam exec -- make USE_SASS=no all
        working-directory: template
